1 verstka
yessimkhanov/stonks pull request #1
Opened 2024-11-29 17:12 UTC by yessimkhanov

2024-12-03 07:01 UTC, Amirzzzhan requested changes
Add Swift-lint-tool

2024-12-03 07:01 UTC, Amirzzzhan commented on stocks/stocks/SceneDelegate.swift
> +        let navController = UINavigationController(rootViewController: mainVC) // Embed in UINavigationController
remove comments

2024-12-03 07:01 UTC, Amirzzzhan commented on stocks/stocks/StocksView.swift
> +class StocksView : UIView {
final class StocksView: UIView {

2024-12-03 07:01 UTC, Amirzzzhan commented on stocks/stocks/StocksView.swift
> +//            buttonStack.trailingAnchor.constraint(equalTo: self.trailingAnchor, constant: -20),
remove comments

2024-12-03 07:01 UTC, Amirzzzhan commented on stocks/stocks/StocksView.swift
> +    private func addSubViews() {
addSubviews*

2024-12-03 07:01 UTC, Amirzzzhan commented on stocks/stocks/StocksView.swift
> +        button.setTitleColor(.systemGray2, for: .normal)
remove comments

2024-12-03 07:01 UTC, Amirzzzhan commented on stocks/stocks/TableViewCell.swift
> +class TableViewCell: UITableViewCell {
naming should be precise

2024-12-03 07:01 UTC, Amirzzzhan commented on stocks/stocks/TableViewCell.swift
> +    weak var delegate : VCDelegate?
Не понятно что такое VCDelegate

2024-12-03 07:01 UTC, Amirzzzhan commented on stocks/stocks/TableViewCell.swift
> +protocol VCDelegate: AnyObject {
протокол надо выше класса написать

2024-12-03 07:01 UTC, Amirzzzhan commented on stocks/stocks/TableViewCell.swift
> +    @objc func starButtonPressed() {
@objc private

2024-12-03 07:01 UTC, Amirzzzhan commented on stocks/stocks/TableViewCell.swift
> +    func configure(logo: UIImage, name: String, abbrv: String, price: Double, background : UIColor, isFavourite: Bool, indexPath: Int) {
func configure(
   logo: UIIMage,
   name: String,
   abbrv: String,
   ...

2024-12-03 07:01 UTC, Amirzzzhan commented on stocks/stocks/ViewController.swift
> +final class ViewController: UIViewController, UISearchBarDelegate, UISearchResultsUpdating{
UISearchBarDelegate, UISearchResultsUpdating - должно быть отдельно в extension

2024-12-03 07:01 UTC, Amirzzzhan commented on stocks/stocks/ViewController.swift
> +    private var stocksAppViews : StocksView!
stockAppView = {
    let view = StocksView()
}()

2024-12-03 07:01 UTC, Amirzzzhan commented on stocks/stocks/ViewController.swift
> +    private var currentStateOfButtons = "Stocks"
вместо "Stocks" создай 'enum State'

2024-12-03 07:01 UTC, Amirzzzhan commented on stocks/stocks/ViewController.swift
> +    @objc func stocksButtonPressed() {
@objc
private func stocksButtonPressed()

2024-12-03 07:01 UTC, Amirzzzhan commented on stocks/stocks/ViewController.swift
> +        if currentStateOfButtons != "Stocks" {
use guard

2024-12-03 07:01 UTC, Amirzzzhan commented on stocks/stocks/ViewController.swift
> +        if currentStateOfButtons == "Stocks" {
switch state {
case .stocks:
case .favourites:
}

2024-12-03 07:01 UTC, Amirzzzhan commented on stocks/stocks/ViewController.swift
> +        if currentStateOfButtons == "Stocks" {
let company: 'Type'  = {
   switch state {
    case .favourite:
         return dataSourceForTableView.favouriteCompanies[indexPath.row]
     case .stocks:
         return dataSourceForTableView.companies[indexPath.row]
    }
}()

...
 remaining code

2024-12-03 07:01 UTC, Amirzzzhan commented on stocks/stocks/ViewController.swift
> +            if (indexPath.row % 2 == 0){
var backgroundColor: UIColor = indexPath.row % 2 == 0 ? .white : .lightGray

2024-12-03 07:01 UTC, Amirzzzhan commented on stocks/stocks/ViewController.swift
> +            cell.configure(logo: company.logo,
cell.configure(
     logo: company.logo,
     ....

2024-12-03 07:01 UTC, Amirzzzhan commented on stocks/stocks/ViewController.swift
> +            let companyToRemove = dataSourceForTableView.companies[indexPath]
presenter.updateStockState

2024-12-03 09:44 UTC, yessimkhanov commented on stocks/stocks/ViewController.swift
> +    private var currentStateOfButtons = "Stocks"
ok

2024-12-10 07:19 UTC, Amirzzzhan requested changes

2024-12-10 07:19 UTC, Amirzzzhan commented on stocks/stocks/StateOfButtons.swift
> +}
удалить файл

2024-12-10 07:19 UTC, Amirzzzhan commented on stocks/stocks/StateOfButton.swift
> +}
добавить в StocksPresenter

2024-12-10 07:19 UTC, Amirzzzhan commented on stocks/stocks/Protocols.swift
> +protocol PresenterProtocol: AnyObject {
StocksPresenterProtocol

2024-12-10 07:19 UTC, Amirzzzhan commented on stocks/stocks/Protocols.swift
> +protocol TickerCellDelegate: AnyObject {
protocol в TableViewCell файл

2024-12-10 07:19 UTC, Amirzzzhan commented on stocks/stocks/SceneDelegate.swift
> +        let mainVC = ViewController()
Нужно создать presenter и viewController отдельно и связать их здесь

2024-12-10 07:19 UTC, Amirzzzhan commented on stocks/stocks/StocksPresenter.swift
> +        return 68
этот код в VC

2024-12-10 07:19 UTC, Amirzzzhan commented on stocks/stocks/StocksPresenter.swift
> +    func markFavourite(at index: Int, for state: StateOfButton) {
убрать for state: StateOfButton параметр

2024-12-10 07:19 UTC, Amirzzzhan commented on stocks/stocks/TickerCell.swift
> +        let button = UIButton(type: .system)
делай lazy и добавь addTarget здесь

2024-12-10 07:19 UTC, Amirzzzhan commented on stocks/stocks/TickerCell.swift
> +        indexPath: Int) {
перед ) нужен newline

2024-12-10 07:19 UTC, Amirzzzhan commented on stocks/stocks/TickerCell.swift
> +        if isFavourite {
use ternary operator

2024-12-10 07:19 UTC, Amirzzzhan commented on stocks/stocks/TickerCell.swift
> +            }
else не нужен

2024-12-10 07:19 UTC, Amirzzzhan commented on stocks/stocks/TickerCell.swift
> +        if isFavourite == false {
nit: !isFavourite

2024-12-10 07:19 UTC, Amirzzzhan commented on stocks/stocks/TickerCell.swift
> +    private func starButtonPressed() {
эту логику метода убрать в презентер

2024-12-10 07:19 UTC, Amirzzzhan commented on stocks/stocks/ViewController.swift
> +    var dataSourceForTableView = CompanyDataSource()
move to scenedelegate

2024-12-10 07:19 UTC, Amirzzzhan commented on stocks/stocks/StocksView.swift
> +        button.setTitleColor(UIColor(rgb: 0x1A1A1A), for: .normal)
add addTarget for UIButtons

2024-12-10 07:19 UTC, Amirzzzhan commented on stocks/stocks/ViewController.swift
> +        stocksAppViews.stocksButton.addTarget(self, action: #selector(stocksButtonPressed), for: .touchUpInside)
дурыс емес

2024-12-10 07:19 UTC, Amirzzzhan commented on stocks/stocks/ViewController.swift
> +            stocksAppViews.tableView.reloadData()
delete

2024-12-10 07:19 UTC, Amirzzzhan commented on stocks/stocks/Protocols.swift
> +    func reloadTableView()
private var stocks: [Company]

func reloadTableView(stocks: [Company]) {
     self.stocks = stocks
     self.tableView.reloadData()
}

и тогда можно удалить 20, 21 строчку

2024-12-23 06:50 UTC, Amirzzzhan commented on stocks/stocks/StocksPresenter.swift
> +    init(view: ViewProtocol, dataSource: CompanyDataSource) {
init(view: , dataSource: , manager: )

2024-12-27 11:18 UTC, merged